#!/usr/bin/env python3
"""PERILUNE sprite pipeline: prompt spec -> Nano Banana (Gemini image API) ->
style enforcement -> web-skin injection -> screenshot.

A "render unit" is the atom the stages iterate: the base asset PLUS any per-asset
`states` (e.g. machine on/off/broken; the base sprite is the default/"on" state) and
`frames` (a pawn walk cycle; the base sprite is the idle pose). Assets that declare
neither yield exactly one unit — the historic behaviour, byte-for-byte. Unit files are
stemmed `<name>` (base), `<name>@<state>`, `<name>@f<k>`; the integrate stage folds them
into APPEND-ONLY SPRITE_STATES / SPRITE_FRAMES maps beside the untouched SPRITE_URIS.

Stages (chainable, each idempotent; state lives in the spec's work dir):
  generate   call the image API, save N candidates per unit + contact sheet.
             Units whose processed sprite already exists are skipped (--force to regen),
             so a committed set (candidates are gitignored) generates ONLY new
             state/frame units without disturbing the shipped base art.
  select     pick one candidate per unit (selection.json; defaults to 0). A unit with no
             candidate but an existing processed sprite is left as-is (already-final art).
  process    key background, downscale to tile size, enforce style, for every unit that
             has a freshly-selected raw (others keep their committed processed sprite)
             (32px spec: shared-palette quantize w/ protected accents;
              128px spec: hue harmonization toward the spec's hue centers)
  integrate  write data URIs + tile size into Client.html between the SPRITEGEN markers
             (procedural fallback untouched); emits SPRITE_URIS and, append-only, the
             SPRITE_STATES / SPRITE_FRAMES maps (absent files -> absent keys, so a client
             built before these existed keeps falling back to the base sprite)
  shot       launch PeriluneWeb headless, screenshot, kill it
  all        generate -> select -> process -> integrate -> shot

Usage:
  GEMINI_API_KEY=... python3 art/spritegen/run.py --spec art/spritegen/spec_steampunk.json --stage all
  python3 art/spritegen/run.py --spec ... --stage process,integrate,shot   # rerun without regenerating
  python3 art/spritegen/run.py --spec ... --stage generate --only anchor_pawn@f  # one unit family

The API model defaults to Nano Banana Pro; override with --model
(e.g. gemini-2.5-flash-image for Nano Banana 1) if the id has moved.
"""
import argparse, base64, io, json, os, subprocess, sys, time
from pathlib import Path

from PIL import Image

REPO = Path(__file__).resolve().parents[2]
CLIENT_HTML = REPO / "hosts/web/Client.html"
PORTRAITS_DIR = REPO / "client/assets/portraits"
PORTRAITS_MANIFEST = REPO / "client/assets/portraits.g.js"
MARK_BEGIN, MARK_END = "// SPRITEGEN BEGIN (generated by tools/spritegen/run.py — do not hand-edit)", "// SPRITEGEN END"
API_URL = "https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent"


def load_spec(path):
    spec = json.loads(Path(path).read_text())
    # Work dir lives OUTSIDE Assets/ so Unity never imports candidate PNGs.
    spec["_work"] = REPO / "art/spritegen/work" / spec["name"]
    spec["_dir"] = Path(path).resolve().parent
    (spec["_work"] / "candidates").mkdir(parents=True, exist_ok=True)
    (spec["_work"] / "processed").mkdir(parents=True, exist_ok=True)
    return spec


# ----------------------------------------------------------------------- units
def frame_prompt_list(asset):
    """Prompts for a pawn walk cycle. `frames` is either an explicit list of prompt
    strings (full authorial control) or an int N (synthesize N mid-stride poses off the
    base prompt). Empty/absent -> no frame units."""
    fr = asset.get("frames")
    if not fr:
        return []
    if isinstance(fr, list):
        return [str(p) for p in fr]
    n = int(fr)
    base = asset["prompt"].strip()
    return [base + (f"\n\nWalk-cycle frame {k + 1} of {n}: mid-stride walking pose, legs "
                    f"and arms shifted for step {k + 1}, exactly the same character, palette, "
                    f"proportions and top-down 3/4 angle as the idle pose.")
            for k in range(n)]


def iter_units(spec):
    """Yield the render units for a spec: each base asset, then its state variants, then
    its frame variants. A unit is a dict {uid, prompt, asset, role, kind[, state|frame]};
    `uid` is the processed-file stem and `asset` carries the shared keyed/fill/facing
    metadata. APPEND-ONLY: an asset with no `states`/`frames` yields exactly one unit."""
    for asset in spec["assets"]:
        yield {"uid": asset["name"], "prompt": asset["prompt"], "asset": asset,
               "role": asset["role"], "kind": "base"}
        for state, prompt in (asset.get("states") or {}).items():
            yield {"uid": f"{asset['name']}@{state}", "prompt": prompt, "asset": asset,
                   "role": asset["role"], "kind": "state", "state": state}
        for k, prompt in enumerate(frame_prompt_list(asset)):
            yield {"uid": f"{asset['name']}@f{k}", "prompt": prompt, "asset": asset,
                   "role": asset["role"], "kind": "frame", "frame": k}


# --------------------------------------------------------------------- generate
def api_generate(model, key, prompt, size_hint):
    import requests
    body = {
        "contents": [{"parts": [{"text": prompt}]}],
        "generationConfig": {"responseModalities": ["IMAGE"]},
    }
    if size_hint:  # Nano Banana Pro accepts imageConfig; older models reject it -> retry without
        body["generationConfig"]["imageConfig"] = {"aspectRatio": "1:1", "imageSize": size_hint}
    r = None
    for attempt in range(1, 5):
        try:
            r = requests.post(API_URL.format(model=model), headers={"x-goog-api-key": key}, json=body, timeout=180)
        except (requests.Timeout, requests.ConnectionError) as e:
            # Transient network hiccups must not kill a long batch — back off and retry.
            if attempt == 4:
                raise
            print(f"  api retry {attempt} after {type(e).__name__}"); time.sleep(10 * attempt)
            continue
        if r.status_code == 400 and size_hint and "imageConfig" in body["generationConfig"]:
            body["generationConfig"].pop("imageConfig", None)
            continue
        if r.status_code in (429, 500, 502, 503, 504) and attempt < 4:
            print(f"  api retry {attempt} after HTTP {r.status_code}"); time.sleep(10 * attempt)
            continue
        r.raise_for_status()
        break
    data = r.json()
    cands = data.get("candidates") or [{}]
    for part in cands[0].get("content", {}).get("parts", []):
        blob = part.get("inlineData") or part.get("inline_data")
        if blob:
            return Image.open(io.BytesIO(base64.b64decode(blob["data"]))).convert("RGBA")
    raise RuntimeError(f"no image in response: {json.dumps(data)[:400]}")


def api_key():
    for name in ("GEMINI_API_KEY", "GOOGLE_API_KEY"):
        if os.environ.get(name):
            return os.environ[name]
    env = REPO / ".env"  # tolerant: any 'name = value' line whose name mentions gemini
    if env.exists():
        for line in env.read_text().splitlines():
            if line.lstrip().startswith("#"):
                continue
            if "=" in line and "gemin" in line.split("=")[0].lower():
                return line.split("=", 1)[1].strip().strip('"').strip("'")
    return None


def stage_generate(spec, model, candidates, force=False, only=None):
    key = api_key()
    if not key:
        sys.exit("generate: set GEMINI_API_KEY (or GOOGLE_API_KEY), or put a gemini key line in .env")
    units = [u for u in iter_units(spec) if not only or only in u["uid"]]
    for u in units:
        processed = spec["_work"] / "processed" / f"{u['uid']}.png"
        if processed.exists() and not force:
            # Committed set: candidates are gitignored but the final sprite is present.
            # Skip so a state/frame pass never re-bills the base art (--force overrides).
            print(f"generate: {u['uid']} already processed, skipping (--force to regen)")
            continue
        prompt = spec["style_block"].strip() + "\n\n" + u["prompt"].strip()
        for i in range(candidates):
            out = spec["_work"] / "candidates" / f"{u['uid']}_{i}.png"
            if out.exists():
                print(f"generate: {out.name} exists, skipping")
                continue
            print(f"generate: {u['uid']} candidate {i} ...")
            img = api_generate(model, key, prompt, spec.get("api_image_size"))
            img.save(out)
            time.sleep(spec.get("api_pause_s", 2))
    contact_sheet(spec, "candidates", cols=candidates, uids=[u["uid"] for u in units])


# ---------------------------------------------------------------------- select
def stage_select(spec):
    sel_path = spec["_work"] / "selection.json"
    sel = json.loads(sel_path.read_text()) if sel_path.exists() else {}
    units = list(iter_units(spec))
    # Backfill defaults for freshly-generated units without disturbing existing picks;
    # only register a unit that actually has a candidate 0 (so a blocked-generation run
    # never rewrites the committed selection.json).
    changed = False
    for u in units:
        if u["uid"] not in sel and (spec["_work"] / "candidates" / f"{u['uid']}_0.png").exists():
            sel[u["uid"]] = 0
            changed = True
    if changed or not sel_path.exists():
        sel_path.write_text(json.dumps(sel, indent=2))
        print(f"select: default-registered new units -> {sel_path}")
    for u in units:
        src = spec["_work"] / "candidates" / f"{u['uid']}_{sel.get(u['uid'], 0)}.png"
        if not src.exists():
            # No candidate for this unit. If we already have its final processed sprite
            # (committed art whose candidates are gitignored), keep it. Otherwise it is a
            # genuine gap.
            if (spec["_work"] / "processed" / f"{u['uid']}.png").exists():
                continue
            sys.exit(f"select: missing {src} — run the generate stage (or place files there by hand)")
        Image.open(src).convert("RGBA").save(spec["_work"] / f"{u['uid']}_raw.png")
    print("select: raw picks staged")


# --------------------------------------------------------------------- process
def key_background(img, spec, asset=None):
    px = img.load()
    # Per-asset key override: an asset whose ART needs the spec's key colour (e.g.
    # green foliage under a green spec key) declares its own contrasting key.
    key = tuple((asset or {}).get("key_color") or spec.get("key_color", [255, 0, 255]))
    tol = spec.get("key_tolerance", 70)
    # The fringe pass follows the key hue: channels the key drives high must
    # dominate the ones it drives low (magenta key: r,b >> g; green key: g >> r,b).
    # Catches the dark anti-aliased fringe the generator blends toward the key.
    hi = [i for i in range(3) if key[i] > 127]
    lo = [i for i in range(3) if key[i] <= 127]
    for y in range(img.height):
        for x in range(img.width):
            c = px[x, y]
            boxed = all(abs(c[i] - key[i]) < tol for i in range(3))
            fringe = (hi and lo
                      and all(c[i] > 60 for i in hi)
                      and all(c[i] < min(c[j] for j in hi) * 0.62 for i in lo))
            if boxed or fringe:
                px[x, y] = (0, 0, 0, 0)
    return img


def sat(c):
    mx, mn = max(c), min(c)
    return 0 if mx == 0 else (mx - mn) / mx


def quantize_set(images, spec):
    """32px mode: one shared palette, chromatic accents in a protected bucket."""
    smin, vmin = spec.get("accent_sat_min", 0.25), spec.get("accent_val_min", 70)
    pool = [p[:3] for im in images.values() for p in im.getdata() if p[3] > 0]
    accents = [c for c in pool if sat(c) >= smin and max(c) > vmin]
    greys = [c for c in pool if not (sat(c) >= smin and max(c) > vmin)]

    def quant(colors, k):
        if not colors:
            return []
        strip = Image.new("RGB", (len(colors), 1)); strip.putdata(colors)
        n = min(k, len(set(colors)))
        pal = strip.quantize(colors=n, method=Image.MEDIANCUT).getpalette()
        return [tuple(pal[i * 3:i * 3 + 3]) for i in range(n)]

    grey_pal = quant(greys, spec.get("palette_greys", 18))
    accent_pal = quant(accents, spec.get("palette_accents", 6))

    def nearest(c):
        cand = accent_pal if (sat(c) >= smin and max(c) > vmin) and accent_pal else grey_pal
        return min(cand, key=lambda p: sum((p[i] - c[i]) ** 2 for i in range(3)))

    for im in images.values():
        px = im.load()
        for y in range(im.height):
            for x in range(im.width):
                r, g, b, a = px[x, y]
                if a:
                    px[x, y] = (*nearest((r, g, b)), 255)
    return images


def harmonize_set(images, spec):
    """128px mode: pull chromatic hues toward the spec's hue centers; no color-count cap."""
    import colorsys
    centers = spec.get("hue_centers_deg", [30, 15, 170])
    pull = spec.get("hue_pull", 0.6)
    smin = spec.get("harmonize_sat_min", 0.18)
    for im in images.values():
        px = im.load()
        for y in range(im.height):
            for x in range(im.width):
                r, g, b, a = px[x, y]
                if not a:
                    continue
                h, s, v = colorsys.rgb_to_hsv(r / 255, g / 255, b / 255)
                if s < smin:
                    continue
                deg = h * 360
                target = min(centers, key=lambda c: min(abs(deg - c), 360 - abs(deg - c)))
                delta = ((target - deg + 180) % 360) - 180
                nh = ((deg + delta * pull) % 360) / 360
                nr, ng, nb = colorsys.hsv_to_rgb(nh, s, v)
                px[x, y] = (int(nr * 255), int(ng * 255), int(nb * 255), a)
    return images


def seam_report(name, im):
    w, h = im.size
    lr = sum(sum(abs(im.getpixel((0, y))[i] - im.getpixel((w - 1, y))[i]) for i in range(3)) for y in range(h)) / (h * 3)
    tb = sum(sum(abs(im.getpixel((x, 0))[i] - im.getpixel((x, h - 1))[i]) for i in range(3)) for x in range(w)) / (w * 3)
    ok = "clean" if max(lr, tb) < 12 else "check the axis you tile on"
    print(f"process: {name} seam deltas L/R={lr:.1f} T/B={tb:.1f} ({ok})")


def autocrop_margin(im, name, max_frac=0.35):
    """Generators love putting 'objects' on a plain frame. Detect a border ring that
    stays near the corner colour and crop to the real texture (tileables especially —
    a baked margin renders as a grid of gutters in-game)."""
    rgb = im.convert("RGB")
    w, h = rgb.size
    corner = rgb.getpixel((1, 1))

    def ring_is_margin(d):
        pts = []
        step = max(1, (w - 2 * d) // 48)
        for x in range(d, w - d, step):
            pts += [rgb.getpixel((x, d)), rgb.getpixel((x, h - 1 - d))]
        for y in range(d, h - d, step):
            pts += [rgb.getpixel((d, y)), rgb.getpixel((w - 1 - d, y))]
        close = sum(1 for p in pts if sum(abs(p[i] - corner[i]) for i in range(3)) < 60)
        return close / max(1, len(pts)) > 0.85

    d = 0
    while d < int(w * max_frac) and ring_is_margin(d):
        d += 1
    if d > max(2, w // 64):
        print(f"process: {name} auto-cropped a {d}px baked margin")
        return im.crop((d, d, w - d, h - d))
    return im


def normalize_fill(im, tile, fill, name, pixel_mode):
    """Proportion-true scale: crop the keyed object to its alpha bbox and size its
    longest side to fill*tile, centered. Generators fill frames inconsistently
    (a chair ballooning past a med-bed) — this grounds relative scale across the
    whole set from one number per asset."""
    bbox = im.getbbox()
    if bbox is None:
        return im.resize((tile, tile), Image.NEAREST if pixel_mode else Image.LANCZOS)
    obj = im.crop(bbox)
    scale = fill * tile / max(obj.width, obj.height)
    w, h = max(1, round(obj.width * scale)), max(1, round(obj.height * scale))
    obj = obj.resize((w, h), Image.NEAREST if pixel_mode else Image.LANCZOS)
    out = Image.new("RGBA", (tile, tile), (0, 0, 0, 0))
    out.paste(obj, ((tile - w) // 2, (tile - h) // 2), obj)
    print(f"process: {name} fill-normalized to {fill:.0%} of tile")
    return out


def stage_process(spec):
    tile = spec["tile_px"]
    pixel_mode = spec.get("style", "pixel") == "pixel"
    units = list(iter_units(spec))
    asset_of = {u["uid"]: u["asset"] for u in units}
    images = {}
    for u in units:
        raw = spec["_work"] / f"{u['uid']}_raw.png"
        if not raw.exists():
            continue  # no freshly-selected raw — keep whatever processed sprite exists
        asset = u["asset"]
        im = Image.open(raw).convert("RGBA")
        if asset.get("keyed"):
            im = key_background(im, spec, asset)
            if asset.get("fill"):
                im = normalize_fill(im, tile, asset["fill"], u["uid"], pixel_mode)
        elif asset.get("autocrop", True):
            im = autocrop_margin(im, u["uid"])
        if im.size != (tile, tile):
            im = im.resize((tile, tile), Image.NEAREST if pixel_mode else Image.LANCZOS)
        images[u["uid"]] = im
    if not images:
        print("process: no freshly-selected raws — nothing to (re)process")
        return
    images = quantize_set(images, spec) if pixel_mode else harmonize_set(images, spec)
    for uid, im in images.items():
        if asset_of[uid].get("tileable"):
            seam_report(uid, im)
        im.save(spec["_work"] / "processed" / f"{uid}.png", optimize=True)
    contact_sheet(spec, "processed", cols=1, uids=[u["uid"] for u in units])
    print(f"process: {len(images)} sprites -> {spec['_work'] / 'processed'}")


def contact_sheet(spec, sub, cols, uids=None):
    names = uids if uids is not None else [a["name"] for a in spec["assets"]]
    cell = 128
    files = []
    for n in names:
        if cols == 1:
            files.append([spec["_work"] / sub / f"{n}.png"])
        else:
            files.append([spec["_work"] / sub / f"{n}_{i}.png" for i in range(cols)])
    sheet = Image.new("RGBA", (cols * cell, len(names) * cell), (20, 22, 28, 255))
    for r, row in enumerate(files):
        for c, f in enumerate(row):
            if f.exists():
                im = Image.open(f).convert("RGBA").resize((cell, cell), Image.NEAREST)
                sheet.paste(im, (c * cell, r * cell), im)
    out = spec["_work"] / f"contact_{sub}.png"
    sheet.save(out)
    print(f"{sub}: contact sheet -> {out}")


# ------------------------------------------------------------------- integrate
def _datauri(path):
    buf = io.BytesIO()
    Image.open(path).save(buf, "PNG", optimize=True)
    return "data:image/png;base64," + base64.b64encode(buf.getvalue()).decode()


def stage_integrate(spec):
    html = CLIENT_HTML.read_text()
    if MARK_BEGIN not in html or MARK_END not in html:
        sys.exit(f"integrate: markers not found in {CLIENT_HTML} — add them around the sprite block first")
    proc = spec["_work"] / "processed"
    uris = {a["role"]: _datauri(proc / f"{a['name']}.png") for a in spec["assets"]}
    # Facing metadata: which way the depicted object faces in the art (N/E/S/W).
    # The client rotates context-sensitively (chair toward its table, bed head to
    # the wall) relative to this canonical direction.
    facings = {a["role"]: a["facing"] for a in spec["assets"] if a.get("facing")}
    # Sprites with baked 3/4 perspective only read correctly in their painted
    # direction — the client must never quarter-turn them.
    no_rotate = [a["role"] for a in spec["assets"] if a.get("rotatable") is False]
    # APPEND-ONLY animation maps. SPRITE_STATES[role][state] is a powered variant (the base
    # sprite is the default/"on" state, never duplicated here); SPRITE_FRAMES[role] is the
    # walk cycle (the base sprite is the idle pose). A missing file -> a missing key, so a
    # client that predates these maps keeps drawing SPRITE_URIS[role] unchanged.
    states, frames = {}, {}
    for asset in spec["assets"]:
        role = asset["role"]
        for state in (asset.get("states") or {}):
            p = proc / f"{asset['name']}@{state}.png"
            if p.exists():
                states.setdefault(role, {})[state] = _datauri(p)
        arr = [_datauri(proc / f"{asset['name']}@f{k}.png")
               for k in range(len(frame_prompt_list(asset)))
               if (proc / f"{asset['name']}@f{k}.png").exists()]
        if arr:
            frames[role] = arr
    lines = [MARK_BEGIN,
             f"const SPRITE_TILE = {spec['tile_px']};",
             "const SPRITE_FACING = " + json.dumps(facings) + ";",
             "const SPRITE_NO_ROTATE = " + json.dumps(no_rotate) + ";",
             "const SPRITE_URIS = {"]
    lines += [f"  {role}: '{uri}'," for role, uri in uris.items()]
    lines += ["};"]
    if states:
        lines += ["const SPRITE_STATES = {"]
        for role, sm in states.items():
            lines.append(f"  {role}: {{")
            lines += [f"    {st}: '{uri}'," for st, uri in sm.items()]
            lines.append("  },")
        lines += ["};"]
    else:
        lines += ["const SPRITE_STATES = {};"]
    if frames:
        lines += ["const SPRITE_FRAMES = {"]
        for role, arr in frames.items():
            lines.append(f"  {role}: [")
            lines += [f"    '{uri}'," for uri in arr]
            lines.append("  ],")
        lines += ["};"]
    else:
        lines += ["const SPRITE_FRAMES = {};"]
    lines += [MARK_END]
    pre, rest = html.split(MARK_BEGIN, 1)
    _, post = rest.split(MARK_END, 1)
    CLIENT_HTML.write_text(pre + "\n".join(lines) + post)
    n_states = sum(len(v) for v in states.values())
    n_frames = sum(len(v) for v in frames.values())
    print(f"integrate: {len(uris)} sprites + {n_states} states + {n_frames} frames "
          f"@ {spec['tile_px']}px -> {CLIENT_HTML.name}")


# ------------------------------------------------------------------------ shot
def stage_shot(spec):
    port = 8341
    srv = subprocess.Popen(
        [os.path.expanduser("~/.dotnet/dotnet"), "run", "--project", str(REPO / "hosts/web"), "--", "--port", str(port)],
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    try:
        time.sleep(8)
        out = spec["_work"] / "shot.png"
        subprocess.run(["/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
                        "--headless", "--disable-gpu", f"--screenshot={out}",
                        "--window-size=2400,1000", "--virtual-time-budget=5000",
                        f"http://localhost:{port}"], check=True, capture_output=True)
        print(f"shot: {out}")
    finally:
        srv.terminate()
        try:
            srv.wait(timeout=5)
        except subprocess.TimeoutExpired:
            srv.kill()


# =====================================================================================
# Portrait mode (A2). A `"mode": "portrait"` spec has no `assets`; its render units come
# from a persona fixture (hosts/scenario dump-personas). Prompts are woven from persona
# TRAITS / ROLE / FEARS / SPEECH — never the backstory, which carries spoilers. Output is
# opaque 256px busts committed under client/assets/portraits/ plus a {key:{file}} manifest.
# =====================================================================================
def load_personas(spec):
    path = Path(spec["personas"])
    if not path.is_absolute():
        path = spec["_dir"] / path
    return json.loads(path.read_text())


def portrait_prompt(spec, persona):
    """Weave a portrait prompt from persona fields the art may safely see. The backstory
    hint (spoilery specifics) is deliberately NOT consulted — only role, traits, fears as
    mood, and speech style as bearing."""
    block = spec["style_block"].strip()
    role = persona.get("rolePreRaid") or persona.get("role") or "crew member"
    traits = ", ".join(persona.get("traits", [])[:3])
    fears = persona.get("fears", [])
    speech = (persona.get("speechStyle") or "").strip()
    parts = [
        block,
        f"Subject: a {role} of the ship's crew.",
        f"Character read: {traits}." if traits else "",
        f"Bearing and expression: {speech}." if speech else "",
        f"A quiet weight behind the eyes — someone who carries {fears[0]}." if fears else "",
    ]
    return "\n\n".join(p for p in parts if p)


def portrait_units(spec):
    for p in load_personas(spec):
        yield {"uid": p["key"], "prompt": portrait_prompt(spec, p), "persona": p}


def stage_portrait_generate(spec, model, candidates, force=False, only=None):
    key = api_key()
    if not key:
        sys.exit("generate: set GEMINI_API_KEY (or GOOGLE_API_KEY), or put a gemini key line in .env")
    units = [u for u in portrait_units(spec) if not only or only in u["uid"]]
    for u in units:
        if (spec["_work"] / "processed" / f"{u['uid']}.png").exists() and not force:
            print(f"generate: {u['uid']} already processed, skipping (--force to regen)")
            continue
        for i in range(candidates):
            out = spec["_work"] / "candidates" / f"{u['uid']}_{i}.png"
            if out.exists():
                print(f"generate: {out.name} exists, skipping")
                continue
            print(f"generate: {u['uid']} candidate {i} ...")
            img = api_generate(model, key, u["prompt"], spec.get("api_image_size"))
            img.save(out)
            time.sleep(spec.get("api_pause_s", 2))
    contact_sheet(spec, "candidates", cols=candidates, uids=[u["uid"] for u in units])


def stage_portrait_select(spec):
    sel_path = spec["_work"] / "selection.json"
    sel = json.loads(sel_path.read_text()) if sel_path.exists() else {}
    units = list(portrait_units(spec))
    changed = False
    for u in units:
        if u["uid"] not in sel and (spec["_work"] / "candidates" / f"{u['uid']}_0.png").exists():
            sel[u["uid"]] = 0
            changed = True
    if changed or not sel_path.exists():
        sel_path.write_text(json.dumps(sel, indent=2))
    for u in units:
        src = spec["_work"] / "candidates" / f"{u['uid']}_{sel.get(u['uid'], 0)}.png"
        if not src.exists():
            if (spec["_work"] / "processed" / f"{u['uid']}.png").exists():
                continue
            sys.exit(f"select: missing {src} — run the generate stage (or place files there by hand)")
        Image.open(src).convert("RGBA").save(spec["_work"] / f"{u['uid']}_raw.png")
    print("select: raw picks staged")


def _center_square(im):
    w, h = im.size
    s = min(w, h)
    return im.crop(((w - s) // 2, (h - s) // 2, (w - s) // 2 + s, (h - s) // 2 + s)) if w != h else im


def stage_portrait_process(spec):
    px = spec.get("portrait_px", 256)
    units = list(portrait_units(spec))
    images = {}
    for u in units:
        raw = spec["_work"] / f"{u['uid']}_raw.png"
        if not raw.exists():
            continue  # no freshly-selected raw — keep any committed portrait
        im = _center_square(Image.open(raw).convert("RGBA"))
        if im.size != (px, px):
            im = im.resize((px, px), Image.LANCZOS)
        images[u["uid"]] = im
    if not images:
        print("process: no freshly-selected raws — nothing to (re)process")
        return
    images = harmonize_set(images, spec)  # gentle hue lock toward the cyberpunk palette
    for uid, im in images.items():
        # Busts are opaque (plain dark background is part of the art) — flatten to RGB.
        im.convert("RGB").save(spec["_work"] / "processed" / f"{uid}.png", optimize=True)
    contact_sheet(spec, "processed", cols=1, uids=[u["uid"] for u in units])
    print(f"process: {len(images)} portraits -> {spec['_work'] / 'processed'}")


def _existing_manifest():
    """Prior manifest entries (key -> file) whose PNG still exists on disk. The manifest is
    APPEND-ONLY across specs (A2 procedural personas + A3 authored slice crew coexist): a spec
    integrate keeps every already-committed portrait and only adds/refreshes its own keys, so a
    citizen art built under an earlier spec is never orphaned by a later one."""
    out = {}
    if PORTRAITS_MANIFEST.exists():
        import re
        for m in re.finditer(r'"(pk_[0-9a-f]+)":\s*\{\s*file:\s*"([^"]+)"', PORTRAITS_MANIFEST.read_text()):
            key, f = m.group(1), m.group(2)
            if (REPO / "client/assets" / f).exists():
                out[key] = f
    return out


def stage_portrait_integrate(spec):
    proc = spec["_work"] / "processed"
    PORTRAITS_DIR.mkdir(parents=True, exist_ok=True)
    # Seed with the prior manifest (append-only) so other specs' portraits survive this run.
    manifest = list(_existing_manifest().items())
    have = {k for k, _ in manifest}
    for u in portrait_units(spec):
        src = proc / f"{u['uid']}.png"
        if not src.exists():
            continue
        Image.open(src).save(PORTRAITS_DIR / f"{u['uid']}.png", "PNG", optimize=True)
        if u["uid"] not in have:  # this spec's own keys are refreshed on disk but appended once
            manifest.append((u["uid"], f"portraits/{u['uid']}.png"))
            have.add(u["uid"])
    lines = [
        "// @ts-nocheck",
        "// GENERATED — do not edit. Produced by art/spritegen/run.py (portrait mode) from the",
        "// persona fixture + spec_portraits_cyberpunk.json. Maps a persona portrait key",
        "// (pk_xxxxxxxx — see hosts/scenario PersonaDump.PersonaKey) to its committed PNG under",
        "// client/assets/portraits/. A citizen whose key is absent here keeps the procedural",
        "// silhouette fallback (client/src/ui/portraits.js). Re-run the pipeline to regenerate.",
        "",
        "export const PORTRAITS = {",
    ]
    lines += [f"  {json.dumps(k)}: {{ file: {json.dumps(f)} }}," for k, f in manifest]
    lines += ["};", ""]
    PORTRAITS_MANIFEST.write_text("\n".join(lines))
    print(f"integrate: {len(manifest)} portraits -> {PORTRAITS_DIR}/ + {PORTRAITS_MANIFEST.name}")


# --------------------------------------------------------------------------- check
def stage_check(spec):
    """Structural validation for either spec kind, plus the portrait spoiler guard and
    manifest<->file cross-check. Non-zero exit on any problem (usable in CI)."""
    problems = []
    if spec.get("mode") == "portrait":
        for k in ("name", "style_block", "personas"):
            if k not in spec:
                problems.append(f"portrait spec missing '{k}'")
        try:
            personas = load_personas(spec)
        except Exception as e:  # noqa: BLE001
            problems.append(f"personas fixture unreadable: {e}")
            personas = []
        for p in personas:
            if not str(p.get("key", "")).startswith("pk_"):
                problems.append(f"persona without a pk_ key: {p.get('name', p)}")
        for u in portrait_units(spec):
            bh = (u["persona"].get("backstoryHint") or "").strip()
            if bh and bh in u["prompt"]:
                problems.append(f"{u['uid']}: backstory text leaked into the portrait prompt")
        if PORTRAITS_MANIFEST.exists():
            import re
            for m in re.finditer(r'file:\s*"([^"]+)"', PORTRAITS_MANIFEST.read_text()):
                f = REPO / "client/assets" / m.group(1)
                if not f.exists():
                    problems.append(f"manifest references missing file {f}")
    else:
        for k in ("name", "tile_px", "style_block", "assets"):
            if k not in spec:
                problems.append(f"sprite spec missing '{k}'")
        roles = set()
        for a in spec.get("assets", []):
            for k in ("name", "role", "prompt"):
                if k not in a:
                    problems.append(f"asset missing '{k}': {a.get('name', '?')}")
            roles.add(a.get("role"))
            if "states" in a and not isinstance(a["states"], dict):
                problems.append(f"{a.get('name')}: 'states' must be an object")
            if "frames" in a and not isinstance(a["frames"], (list, int)):
                problems.append(f"{a.get('name')}: 'frames' must be a list or an int")
    if problems:
        for p in problems:
            print("check: FAIL:", p)
        sys.exit(f"check: {len(problems)} problem(s)")
    print(f"check: OK ({'portrait' if spec.get('mode') == 'portrait' else 'sprite'} spec '{spec['name']}')")


SPRITE_STAGES = {"generate": None, "select": stage_select, "process": stage_process,
                 "integrate": stage_integrate, "shot": stage_shot, "check": stage_check}
PORTRAIT_STAGES = {"generate": None, "select": stage_portrait_select,
                   "process": stage_portrait_process, "integrate": stage_portrait_integrate,
                   "check": stage_check}
SPRITE_ALL = ["generate", "select", "process", "integrate", "shot"]
PORTRAIT_ALL = ["generate", "select", "process", "integrate"]
STAGES = SPRITE_STAGES  # back-compat alias for the --stage help text


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--spec", required=True)
    ap.add_argument("--stage", default="all", help="comma list of: " + ",".join(STAGES) + ",all")
    ap.add_argument("--model", default="gemini-3-pro-image-preview")
    ap.add_argument("--candidates", type=int, default=4)
    ap.add_argument("--force", action="store_true",
                    help="regenerate even units that already have a processed sprite")
    ap.add_argument("--only", default=None,
                    help="generate only units whose uid contains this substring")
    args = ap.parse_args()
    spec = load_spec(args.spec)
    portrait = spec.get("mode") == "portrait"
    table = PORTRAIT_STAGES if portrait else SPRITE_STAGES
    gen = stage_portrait_generate if portrait else stage_generate
    default_all = PORTRAIT_ALL if portrait else SPRITE_ALL
    stages = default_all if args.stage == "all" else args.stage.split(",")
    for s in stages:
        if s not in table:
            sys.exit(f"unknown stage {s!r} for a {'portrait' if portrait else 'sprite'} spec")
        print(f"== {s} ==")
        if s == "generate":
            gen(spec, args.model, args.candidates, force=args.force, only=args.only)
        else:
            table[s](spec)

if __name__ == "__main__":
    main()
