#!/usr/bin/env python3
"""PERILUNE sprite pipeline: prompt spec -> Nano Banana (Gemini image API) ->
style enforcement -> web-skin injection -> screenshot.

Stages (chainable, each idempotent; state lives in the spec's work dir):
  generate   call the image API, save N candidates per asset + contact sheet
  select     pick one candidate per asset (selection.json; defaults to 0)
  process    key background, downscale to tile size, enforce style
             (32px spec: shared-palette quantize w/ protected accents;
              128px spec: hue harmonization toward the spec's hue centers)
  integrate  write data URIs + tile size into Client.html between the
             SPRITEGEN markers (procedural fallback untouched)
  shot       launch PeriluneWeb headless, screenshot, kill it
  all        generate -> select -> process -> integrate -> shot

Usage:
  GEMINI_API_KEY=... python3 art/spritegen/run.py --spec art/spritegen/spec_steampunk.json --stage all
  python3 art/spritegen/run.py --spec ... --stage process,integrate,shot   # rerun without regenerating

The API model defaults to Nano Banana Pro; override with --model
(e.g. gemini-2.5-flash-image for Nano Banana 1) if the id has moved.
"""
import argparse, base64, io, json, os, subprocess, sys, time
from pathlib import Path

from PIL import Image

REPO = Path(__file__).resolve().parents[2]
CLIENT_HTML = REPO / "hosts/web/Client.html"
MARK_BEGIN, MARK_END = "// SPRITEGEN BEGIN (generated by tools/spritegen/run.py — do not hand-edit)", "// SPRITEGEN END"
API_URL = "https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent"


def load_spec(path):
    spec = json.loads(Path(path).read_text())
    # Work dir lives OUTSIDE Assets/ so Unity never imports candidate PNGs.
    spec["_work"] = REPO / "art/spritegen/work" / spec["name"]
    (spec["_work"] / "candidates").mkdir(parents=True, exist_ok=True)
    (spec["_work"] / "processed").mkdir(parents=True, exist_ok=True)
    return spec


# --------------------------------------------------------------------- generate
def api_generate(model, key, prompt, size_hint):
    import requests
    body = {
        "contents": [{"parts": [{"text": prompt}]}],
        "generationConfig": {"responseModalities": ["IMAGE"]},
    }
    if size_hint:  # Nano Banana Pro accepts imageConfig; older models reject it -> retry without
        body["generationConfig"]["imageConfig"] = {"aspectRatio": "1:1", "imageSize": size_hint}
    r = None
    for attempt in range(1, 5):
        try:
            r = requests.post(API_URL.format(model=model), headers={"x-goog-api-key": key}, json=body, timeout=180)
        except (requests.Timeout, requests.ConnectionError) as e:
            # Transient network hiccups must not kill a long batch — back off and retry.
            if attempt == 4:
                raise
            print(f"  api retry {attempt} after {type(e).__name__}"); time.sleep(10 * attempt)
            continue
        if r.status_code == 400 and size_hint and "imageConfig" in body["generationConfig"]:
            body["generationConfig"].pop("imageConfig", None)
            continue
        if r.status_code in (429, 500, 502, 503, 504) and attempt < 4:
            print(f"  api retry {attempt} after HTTP {r.status_code}"); time.sleep(10 * attempt)
            continue
        r.raise_for_status()
        break
    data = r.json()
    cands = data.get("candidates") or [{}]
    for part in cands[0].get("content", {}).get("parts", []):
        blob = part.get("inlineData") or part.get("inline_data")
        if blob:
            return Image.open(io.BytesIO(base64.b64decode(blob["data"]))).convert("RGBA")
    raise RuntimeError(f"no image in response: {json.dumps(data)[:400]}")


def api_key():
    for name in ("GEMINI_API_KEY", "GOOGLE_API_KEY"):
        if os.environ.get(name):
            return os.environ[name]
    env = REPO / ".env"  # tolerant: any 'name = value' line whose name mentions gemini
    if env.exists():
        for line in env.read_text().splitlines():
            if line.lstrip().startswith("#"):
                continue
            if "=" in line and "gemin" in line.split("=")[0].lower():
                return line.split("=", 1)[1].strip().strip('"').strip("'")
    return None


def stage_generate(spec, model, candidates):
    key = api_key()
    if not key:
        sys.exit("generate: set GEMINI_API_KEY (or GOOGLE_API_KEY), or put a gemini key line in .env")
    for asset in spec["assets"]:
        prompt = spec["style_block"].strip() + "\n\n" + asset["prompt"].strip()
        for i in range(candidates):
            out = spec["_work"] / "candidates" / f"{asset['name']}_{i}.png"
            if out.exists():
                print(f"generate: {out.name} exists, skipping")
                continue
            print(f"generate: {asset['name']} candidate {i} ...")
            img = api_generate(model, key, prompt, spec.get("api_image_size"))
            img.save(out)
            time.sleep(spec.get("api_pause_s", 2))
    contact_sheet(spec, "candidates", cols=candidates)


# ---------------------------------------------------------------------- select
def stage_select(spec):
    sel_path = spec["_work"] / "selection.json"
    if sel_path.exists():
        sel = json.loads(sel_path.read_text())
    else:
        sel = {a["name"]: 0 for a in spec["assets"]}
        sel_path.write_text(json.dumps(sel, indent=2))
        print(f"select: wrote default selection (candidate 0 each) -> {sel_path}")
    for asset in spec["assets"]:
        src = spec["_work"] / "candidates" / f"{asset['name']}_{sel.get(asset['name'], 0)}.png"
        if not src.exists():
            sys.exit(f"select: missing {src} — run the generate stage (or place files there by hand)")
        Image.open(src).convert("RGBA").save(spec["_work"] / f"{asset['name']}_raw.png")
    print("select: raw picks staged")


# --------------------------------------------------------------------- process
def key_background(img, spec, asset=None):
    px = img.load()
    # Per-asset key override: an asset whose ART needs the spec's key colour (e.g.
    # green foliage under a green spec key) declares its own contrasting key.
    key = tuple((asset or {}).get("key_color") or spec.get("key_color", [255, 0, 255]))
    tol = spec.get("key_tolerance", 70)
    # The fringe pass follows the key hue: channels the key drives high must
    # dominate the ones it drives low (magenta key: r,b >> g; green key: g >> r,b).
    # Catches the dark anti-aliased fringe the generator blends toward the key.
    hi = [i for i in range(3) if key[i] > 127]
    lo = [i for i in range(3) if key[i] <= 127]
    for y in range(img.height):
        for x in range(img.width):
            c = px[x, y]
            boxed = all(abs(c[i] - key[i]) < tol for i in range(3))
            fringe = (hi and lo
                      and all(c[i] > 60 for i in hi)
                      and all(c[i] < min(c[j] for j in hi) * 0.62 for i in lo))
            if boxed or fringe:
                px[x, y] = (0, 0, 0, 0)
    return img


def sat(c):
    mx, mn = max(c), min(c)
    return 0 if mx == 0 else (mx - mn) / mx


def quantize_set(images, spec):
    """32px mode: one shared palette, chromatic accents in a protected bucket."""
    smin, vmin = spec.get("accent_sat_min", 0.25), spec.get("accent_val_min", 70)
    pool = [p[:3] for im in images.values() for p in im.getdata() if p[3] > 0]
    accents = [c for c in pool if sat(c) >= smin and max(c) > vmin]
    greys = [c for c in pool if not (sat(c) >= smin and max(c) > vmin)]

    def quant(colors, k):
        if not colors:
            return []
        strip = Image.new("RGB", (len(colors), 1)); strip.putdata(colors)
        n = min(k, len(set(colors)))
        pal = strip.quantize(colors=n, method=Image.MEDIANCUT).getpalette()
        return [tuple(pal[i * 3:i * 3 + 3]) for i in range(n)]

    grey_pal = quant(greys, spec.get("palette_greys", 18))
    accent_pal = quant(accents, spec.get("palette_accents", 6))

    def nearest(c):
        cand = accent_pal if (sat(c) >= smin and max(c) > vmin) and accent_pal else grey_pal
        return min(cand, key=lambda p: sum((p[i] - c[i]) ** 2 for i in range(3)))

    for im in images.values():
        px = im.load()
        for y in range(im.height):
            for x in range(im.width):
                r, g, b, a = px[x, y]
                if a:
                    px[x, y] = (*nearest((r, g, b)), 255)
    return images


def harmonize_set(images, spec):
    """128px mode: pull chromatic hues toward the spec's hue centers; no color-count cap."""
    import colorsys
    centers = spec.get("hue_centers_deg", [30, 15, 170])
    pull = spec.get("hue_pull", 0.6)
    smin = spec.get("harmonize_sat_min", 0.18)
    for im in images.values():
        px = im.load()
        for y in range(im.height):
            for x in range(im.width):
                r, g, b, a = px[x, y]
                if not a:
                    continue
                h, s, v = colorsys.rgb_to_hsv(r / 255, g / 255, b / 255)
                if s < smin:
                    continue
                deg = h * 360
                target = min(centers, key=lambda c: min(abs(deg - c), 360 - abs(deg - c)))
                delta = ((target - deg + 180) % 360) - 180
                nh = ((deg + delta * pull) % 360) / 360
                nr, ng, nb = colorsys.hsv_to_rgb(nh, s, v)
                px[x, y] = (int(nr * 255), int(ng * 255), int(nb * 255), a)
    return images


def seam_report(name, im):
    w, h = im.size
    lr = sum(sum(abs(im.getpixel((0, y))[i] - im.getpixel((w - 1, y))[i]) for i in range(3)) for y in range(h)) / (h * 3)
    tb = sum(sum(abs(im.getpixel((x, 0))[i] - im.getpixel((x, h - 1))[i]) for i in range(3)) for x in range(w)) / (w * 3)
    ok = "clean" if max(lr, tb) < 12 else "check the axis you tile on"
    print(f"process: {name} seam deltas L/R={lr:.1f} T/B={tb:.1f} ({ok})")


def autocrop_margin(im, name, max_frac=0.35):
    """Generators love putting 'objects' on a plain frame. Detect a border ring that
    stays near the corner colour and crop to the real texture (tileables especially —
    a baked margin renders as a grid of gutters in-game)."""
    rgb = im.convert("RGB")
    w, h = rgb.size
    corner = rgb.getpixel((1, 1))

    def ring_is_margin(d):
        pts = []
        step = max(1, (w - 2 * d) // 48)
        for x in range(d, w - d, step):
            pts += [rgb.getpixel((x, d)), rgb.getpixel((x, h - 1 - d))]
        for y in range(d, h - d, step):
            pts += [rgb.getpixel((d, y)), rgb.getpixel((w - 1 - d, y))]
        close = sum(1 for p in pts if sum(abs(p[i] - corner[i]) for i in range(3)) < 60)
        return close / max(1, len(pts)) > 0.85

    d = 0
    while d < int(w * max_frac) and ring_is_margin(d):
        d += 1
    if d > max(2, w // 64):
        print(f"process: {name} auto-cropped a {d}px baked margin")
        return im.crop((d, d, w - d, h - d))
    return im


def normalize_fill(im, tile, fill, name, pixel_mode):
    """Proportion-true scale: crop the keyed object to its alpha bbox and size its
    longest side to fill*tile, centered. Generators fill frames inconsistently
    (a chair ballooning past a med-bed) — this grounds relative scale across the
    whole set from one number per asset."""
    bbox = im.getbbox()
    if bbox is None:
        return im.resize((tile, tile), Image.NEAREST if pixel_mode else Image.LANCZOS)
    obj = im.crop(bbox)
    scale = fill * tile / max(obj.width, obj.height)
    w, h = max(1, round(obj.width * scale)), max(1, round(obj.height * scale))
    obj = obj.resize((w, h), Image.NEAREST if pixel_mode else Image.LANCZOS)
    out = Image.new("RGBA", (tile, tile), (0, 0, 0, 0))
    out.paste(obj, ((tile - w) // 2, (tile - h) // 2), obj)
    print(f"process: {name} fill-normalized to {fill:.0%} of tile")
    return out


def stage_process(spec):
    tile = spec["tile_px"]
    pixel_mode = spec.get("style", "pixel") == "pixel"
    images = {}
    for asset in spec["assets"]:
        im = Image.open(spec["_work"] / f"{asset['name']}_raw.png").convert("RGBA")
        if asset.get("keyed"):
            im = key_background(im, spec, asset)
            if asset.get("fill"):
                im = normalize_fill(im, tile, asset["fill"], asset["name"], pixel_mode)
        elif asset.get("autocrop", True):
            im = autocrop_margin(im, asset["name"])
        if im.size != (tile, tile):
            im = im.resize((tile, tile), Image.NEAREST if pixel_mode else Image.LANCZOS)
        images[asset["name"]] = im
    images = quantize_set(images, spec) if pixel_mode else harmonize_set(images, spec)
    for asset in spec["assets"]:
        im = images[asset["name"]]
        if asset.get("tileable"):
            seam_report(asset["name"], im)
        im.save(spec["_work"] / "processed" / f"{asset['name']}.png", optimize=True)
    contact_sheet(spec, "processed", cols=1)
    print(f"process: {len(images)} sprites -> {spec['_work'] / 'processed'}")


def contact_sheet(spec, sub, cols):
    names = [a["name"] for a in spec["assets"]]
    cell = 128
    files = []
    for n in names:
        if cols == 1:
            files.append([spec["_work"] / sub / f"{n}.png"])
        else:
            files.append([spec["_work"] / sub / f"{n}_{i}.png" for i in range(cols)])
    sheet = Image.new("RGBA", (cols * cell, len(names) * cell), (20, 22, 28, 255))
    for r, row in enumerate(files):
        for c, f in enumerate(row):
            if f.exists():
                im = Image.open(f).convert("RGBA").resize((cell, cell), Image.NEAREST)
                sheet.paste(im, (c * cell, r * cell), im)
    out = spec["_work"] / f"contact_{sub}.png"
    sheet.save(out)
    print(f"{sub}: contact sheet -> {out}")


# ------------------------------------------------------------------- integrate
def stage_integrate(spec):
    html = CLIENT_HTML.read_text()
    if MARK_BEGIN not in html or MARK_END not in html:
        sys.exit(f"integrate: markers not found in {CLIENT_HTML} — add them around the sprite block first")
    uris = {}
    for asset in spec["assets"]:
        buf = io.BytesIO()
        Image.open(spec["_work"] / "processed" / f"{asset['name']}.png").save(buf, "PNG", optimize=True)
        uris[asset["role"]] = "data:image/png;base64," + base64.b64encode(buf.getvalue()).decode()
    # Facing metadata: which way the depicted object faces in the art (N/E/S/W).
    # The client rotates context-sensitively (chair toward its table, bed head to
    # the wall) relative to this canonical direction.
    facings = {a["role"]: a["facing"] for a in spec["assets"] if a.get("facing")}
    # Sprites with baked 3/4 perspective only read correctly in their painted
    # direction — the client must never quarter-turn them.
    no_rotate = [a["role"] for a in spec["assets"] if a.get("rotatable") is False]
    lines = [MARK_BEGIN,
             f"const SPRITE_TILE = {spec['tile_px']};",
             "const SPRITE_FACING = " + json.dumps(facings) + ";",
             "const SPRITE_NO_ROTATE = " + json.dumps(no_rotate) + ";",
             "const SPRITE_URIS = {"]
    lines += [f"  {role}: '{uri}'," for role, uri in uris.items()]
    lines += ["};", MARK_END]
    pre, rest = html.split(MARK_BEGIN, 1)
    _, post = rest.split(MARK_END, 1)
    CLIENT_HTML.write_text(pre + "\n".join(lines) + post)
    print(f"integrate: {len(uris)} sprites @ {spec['tile_px']}px -> {CLIENT_HTML.name}")


# ------------------------------------------------------------------------ shot
def stage_shot(spec):
    port = 8341
    srv = subprocess.Popen(
        [os.path.expanduser("~/.dotnet/dotnet"), "run", "--project", str(REPO / "hosts/web"), "--", "--port", str(port)],
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    try:
        time.sleep(8)
        out = spec["_work"] / "shot.png"
        subprocess.run(["/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
                        "--headless", "--disable-gpu", f"--screenshot={out}",
                        "--window-size=2400,1000", "--virtual-time-budget=5000",
                        f"http://localhost:{port}"], check=True, capture_output=True)
        print(f"shot: {out}")
    finally:
        srv.terminate()
        try:
            srv.wait(timeout=5)
        except subprocess.TimeoutExpired:
            srv.kill()


STAGES = {"generate": None, "select": stage_select, "process": stage_process,
          "integrate": stage_integrate, "shot": stage_shot}

def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--spec", required=True)
    ap.add_argument("--stage", default="all", help="comma list of: " + ",".join(STAGES) + ",all")
    ap.add_argument("--model", default="gemini-3-pro-image-preview")
    ap.add_argument("--candidates", type=int, default=4)
    args = ap.parse_args()
    spec = load_spec(args.spec)
    stages = list(STAGES) if args.stage == "all" else args.stage.split(",")
    for s in stages:
        if s not in STAGES:
            sys.exit(f"unknown stage {s!r}")
        print(f"== {s} ==")
        if s == "generate":
            stage_generate(spec, args.model, args.candidates)
        else:
            STAGES[s](spec)

if __name__ == "__main__":
    main()
